name: 🧪 Test (shared)

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        # this is limited to string | boolean | number (https://github.community/t/can-action-inputs-be-arrays/16457)
        # but we want to pass an array (node_version: "[14, 16, 18]"),
        # so we'll need to manually stringify it for now
        type: string

env:
  CI: true
  CYPRESS_INSTALL_BINARY: 0

jobs:
  build:
    name: ⚙️ Build
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          # this is for the *global* cache, and not `node_modules`
          cache: "yarn"

      - name: 🕵️ Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: 📥 Restore node_modules
        id: yarn-cache
        uses: actions/cache@v3
        with:
          enableCrossOsArchive: true
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 📥 Install deps
        run: yarn --frozen-lockfile

      - name: 🏗 Build
        run: yarn build

      - name: 📤 Cache build
        uses: actions/cache@v3
        with:
          enableCrossOsArchive: true
          path: ./build
          key: remix-build-${{ github.sha }}

  test:
    name: "🧪 Test: (OS: ${{ matrix.os }} Node: ${{ matrix.node }})"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          - windows-latest
        node: ${{ fromJSON(inputs.node_version) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          # this is for the *global* cache, and not `node_modules`
          cache: "yarn"

      - name: 🕵️ Get yarn cache directory path
        if: runner.os != 'Windows'
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: 🕵️ Get yarn cache directory path (Windows)
        if: runner.os == 'Windows'
        id: yarn-cache-dir-path-windows
        run: echo "dir=$(yarn cache dir)" >> ${env:GITHUB_OUTPUT}

      - name: 📥 Restore node_modules
        id: yarn-cache
        uses: actions/cache@v3
        with:
          enableCrossOsArchive: true
          path: ${{ runner.os == 'Windows' && steps.yarn-cache-dir-path-windows.outputs.dir || steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 📥 Install deps
        run: yarn --frozen-lockfile

      - name: 🧪 Run Primary Tests
        run: yarn test:primary

  ubuntu-integration:
    name: '👀 Integration Test: (OS: "ubuntu-latest" Node: "${{ matrix.node }}" Browser: "${{ matrix.browser }}")'
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON(inputs.node_version) }}
        browser: ["chromium", "firefox"]

    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          # this is for the *global* cache, and not `node_modules`
          cache: "yarn"

      - name: 📥 Restore node_modules
        uses: actions/cache@v3
        with:
          enableCrossOsArchive: true
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: 📥 Install deps
        run: yarn --frozen-lockfile

      - name: 👀 Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('@playwright/test/package.json').version)")" >> $GITHUB_ENV

      - name: 📥 Restore playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          enableCrossOsArchive: true
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: 📥 Install Playwright
        run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: 📥 Restore build
        uses: actions/cache@v3
        with:
          enableCrossOsArchive: true
          path: ./build
          key: remix-build-${{ github.sha }}

      - name: 👀 Run Integration Tests ${{ matrix.browser }}
        run: |
          npm pkg delete scripts.pretest:integration
          npm pkg delete scripts.posttest:integration
          yarn test:integration --project=${{ matrix.browser }}

  macos-integration:
    name: '👀 Integration Test: (OS: "macos-latest" Node: "${{ matrix.node }}" Browser: "${{ matrix.browser }}")'
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON(inputs.node_version) }}
        browser: ["webkit"]

    runs-on: macos-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          # this is for the *global* cache, and not `node_modules`
          cache: "yarn"

      - name: 📥 Restore node_modules
        uses: actions/cache@v3
        with:
          enableCrossOsArchive: true
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: 📥 Install deps
        run: yarn --frozen-lockfile

      - name: 👀 Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('@playwright/test/package.json').version)")" >> $GITHUB_ENV

      - name: 📥 Restore playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          enableCrossOsArchive: true
          path: |
            ~/Library/Caches/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: 📥 Install Playwright
        run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: 📥 Restore build
        uses: actions/cache@v3
        with:
          enableCrossOsArchive: true
          path: ./build
          key: remix-build-${{ github.sha }}

      - name: 👀 Run Integration Tests ${{ matrix.browser }}
        run: |
          npm pkg delete scripts.pretest:integration
          npm pkg delete scripts.posttest:integration
          yarn test:integration --project=${{ matrix.browser }}

  windows-integration:
    name: '👀 Integration Test: (OS: "windows-latest" Node: "${{ matrix.node }}" Browser: "${{ matrix.browser }}")'
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJSON(inputs.node_version) }}
        browser: ["edge"]

    runs-on: windows-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          # this is for the *global* cache, and not `node_modules`
          cache: "yarn"

      - name: 📥 Restore node_modules
        uses: actions/cache@v3
        with:
          enableCrossOsArchive: true
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: 📥 Install deps
        run: yarn --frozen-lockfile

      - name: 👀 Get installed Playwright version
        id: playwright-version
        run: |
          chcp 65001 # set code page to utf-8
          echo ("PLAYWRIGHT_VERSION=" + (node -e "console.log(require('@playwright/test/package.json').version)")) >> $env:GITHUB_ENV

      - name: 📥 Restore playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          enableCrossOsArchive: true
          path: |
            %USERPROFILE%\AppData\Local\ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: 📥 Install Playwright
        run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: 📥 Restore build
        uses: actions/cache@v3
        with:
          enableCrossOsArchive: true
          path: ./build
          key: remix-build-${{ github.sha }}

      - name: 👀 Run Integration Tests ${{ matrix.browser }}
        run: |
          npm pkg delete scripts.pretest:integration
          npm pkg delete scripts.posttest:integration
          yarn test:integration --project=${{ matrix.browser }}
